addSbtPlugin("org.scalameta" % "sbt-scalafmt"             % "2.5.4")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix"             % "0.14.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage"            % "2.3.0")
//addSbtPlugin("org.typelevel" % "sbt-tpolecat"             % "0.5.2")
addSbtPlugin("org.typelevel" % "sbt-typelevel-ci-release" % "0.7.7")
