addSbtPlugin("org.scalameta" % "sbt-scalafmt"             % "2.5.2")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix"             % "0.12.1")
addSbtPlugin("org.scoverage" % "sbt-scoverage"            % "2.1.0")
addSbtPlugin("org.typelevel" % "sbt-tpolecat"             % "0.5.0")
addSbtPlugin("org.typelevel" % "sbt-typelevel-ci-release" % "0.6.7")
